### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by hivanov** [goncalopereira/statsd-csharp-client#35]
Hello,

Could you please sign the packages generated? We are very fond of your library, but have to re-download it every time, compile it and sign it ourselves, which is tedious at best.

**Comment by DarrellMozingo** [comment]
Hey hivanov. We've not had any other interest in strong naming and have heard nothing but horror stories about it in general. Since most other .Net packages these days seem to not offer it anymore I'm going to decline doing this for the statsd client too, sorry. If you'd like to submit a repeatable build script that can handle it without breaking backwards compatibility for everyone else we'd be happy to take a look though.
